version: '3'

services:
  cloudpubsub:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command:
      - "gcloud"
      - "beta"
      - "emulators"
      - "pubsub"
      - "start"
      - "--host-port=0.0.0.0:8086"
      - "--project=development"
    ports:
      - "8086:8086"
  server:
    build:
      context: ./pubsub-ui-server
    ports:
      - "50051:50051"
  client:
    build:
      context: ./pubsub-ui-client
    ports:
      - "9091:80"
    links:
      - server
    depends_on:
      - server
