// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pubsub_ui.proto

package pubsubui

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PubSubUI_Fetch_FullMethodName = "/pubsubui.PubSubUI/Fetch"
)

// PubSubUIClient is the client API for PubSubUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PubSubUIClient interface {
	// Fetch PubSub message from the provided PubSub Topic
	Fetch(ctx context.Context, in *TopicSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
}

type pubSubUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPubSubUIClient(cc grpc.ClientConnInterface) PubSubUIClient {
	return &pubSubUIClient{cc}
}

func (c *pubSubUIClient) Fetch(ctx context.Context, in *TopicSubscription, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PubSubUI_ServiceDesc.Streams[0], PubSubUI_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TopicSubscription, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubUI_FetchClient = grpc.ServerStreamingClient[Message]

// PubSubUIServer is the server API for PubSubUI service.
// All implementations must embed UnimplementedPubSubUIServer
// for forward compatibility.
type PubSubUIServer interface {
	// Fetch PubSub message from the provided PubSub Topic
	Fetch(*TopicSubscription, grpc.ServerStreamingServer[Message]) error
	mustEmbedUnimplementedPubSubUIServer()
}

// UnimplementedPubSubUIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPubSubUIServer struct{}

func (UnimplementedPubSubUIServer) Fetch(*TopicSubscription, grpc.ServerStreamingServer[Message]) error {
	return status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedPubSubUIServer) mustEmbedUnimplementedPubSubUIServer() {}
func (UnimplementedPubSubUIServer) testEmbeddedByValue()                  {}

// UnsafePubSubUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PubSubUIServer will
// result in compilation errors.
type UnsafePubSubUIServer interface {
	mustEmbedUnimplementedPubSubUIServer()
}

func RegisterPubSubUIServer(s grpc.ServiceRegistrar, srv PubSubUIServer) {
	// If the following call pancis, it indicates UnimplementedPubSubUIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PubSubUI_ServiceDesc, srv)
}

func _PubSubUI_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TopicSubscription)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubSubUIServer).Fetch(m, &grpc.GenericServerStream[TopicSubscription, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PubSubUI_FetchServer = grpc.ServerStreamingServer[Message]

// PubSubUI_ServiceDesc is the grpc.ServiceDesc for PubSubUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PubSubUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pubsubui.PubSubUI",
	HandlerType: (*PubSubUIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Fetch",
			Handler:       _PubSubUI_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pubsub_ui.proto",
}
