// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/google/wire"
	"github.com/xhsun/gcp-pubsub-ui/pubsub-ui-server/internal/config"
	"github.com/xhsun/gcp-pubsub-ui/pubsub-ui-server/internal/core"
	"github.com/xhsun/gcp-pubsub-ui/pubsub-ui-server/internal/grpc"
	"github.com/xhsun/gcp-pubsub-ui/pubsub-ui-server/internal/infra"
)

// Injectors from wire.go:

func InitializeServer(config2 *config.Config) (*grpc.Server, error) {
	gcpPubSubRepositoryBuilder := infra.NewGCPPubSubRepositoryBuilder(config2)
	messageStreamService := core.NewMessageStreamService(config2, gcpPubSubRepositoryBuilder)
	messageHandler := grpc.NewMessageHandler(messageStreamService)
	server := grpc.NewServer(config2, messageHandler)
	return server, nil
}

// wire.go:

var ServiceBuilderSet = wire.NewSet(infra.NewGCPPubSubRepository, wire.Bind(new(core.IPubSubRepository), new(*infra.GCPPubSubRepository)), infra.NewGCPPubSubRepositoryBuilder, wire.Bind(new(core.IPubSubRepositoryBuilder), new(*infra.GCPPubSubRepositoryBuilder)), core.NewMessageStreamService, wire.Bind(new(core.IMessageStreamService), new(*core.MessageStreamService)))
