// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file pubsub_ui.proto (package pubsubui, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Message, TopicSubscription } from "./pubsub_ui_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service pubsubui.PubSubUI
 */
export const PubSubUI = {
  typeName: "pubsubui.PubSubUI",
  methods: {
    /**
     * Fetch PubSub message from the provided PubSub Topic
     *
     * @generated from rpc pubsubui.PubSubUI.Fetch
     */
    fetch: {
      name: "Fetch",
      I: TopicSubscription,
      O: Message,
      kind: MethodKind.ServerStreaming,
    },
  }
} as const;

