/**
 * @fileoverview gRPC-Web generated client stub for pubsubui
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: pubsub_ui.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as pubsub_ui_pb from './pubsub_ui_pb'; // proto import: "pubsub_ui.proto"


export class PubSubUIClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorFetch = new grpcWeb.MethodDescriptor(
    '/pubsubui.PubSubUI/Fetch',
    grpcWeb.MethodType.SERVER_STREAMING,
    pubsub_ui_pb.TopicSubscription,
    pubsub_ui_pb.Message,
    (request: pubsub_ui_pb.TopicSubscription) => {
      return request.serializeBinary();
    },
    pubsub_ui_pb.Message.deserializeBinary
  );

  fetch(
    request: pubsub_ui_pb.TopicSubscription,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<pubsub_ui_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pubsubui.PubSubUI/Fetch',
      request,
      metadata || {},
      this.methodDescriptorFetch);
  }

}

